#!/usr/bin/env bash
# Generated by Agent Hub — enforces a subset of the Operational Guardrails & Universal Guardrails that
# every generated agent file in this repo was told to follow (see .agent.md / CLAUDE.md / AGENTS.md).
# Zero dependencies on purpose: this must run in CI without an install step, on every stack.
set -euo pipefail

FAIL=0
say_fail() { echo "::error::$1"; FAIL=1; }

echo "Agent Hub guardrail check — scanning changed and tracked files..."

# Only check files git actually tracks, so build output / node_modules / vendored code never trips this.
FILES=$(git ls-files | grep -Ev '(^|/)(node_modules|dist|build|\.next|vendor|\.venv|target)/' || true)

# --- Never Allowed: committed .env files (Operational Guardrails, "Never allowed") ---
ENV_FILES=$(echo "$FILES" | grep -E '(^|/)\.env(\..+)?$' | grep -v '\.env\.example$' || true)
if [ -n "$ENV_FILES" ]; then
  say_fail "A .env file is tracked by git — secrets belong in environment/secret storage, never a committed file: $ENV_FILES"
fi

# --- Never Allowed: an obvious hard-coded secret pattern (Universal Guardrails, Security & Safety) ---
if echo "$FILES" | xargs -r grep -InE '(api[_-]?key|secret[_-]?key|access[_-]?token)\s*[:=]\s*["\047][A-Za-z0-9_\-]{16,}["\047]' 2>/dev/null | grep -v -E '(\.example|\.sample|\.md:)' ; then
  say_fail "A likely hard-coded secret/API key literal was found — read it from environment/secret storage instead."
fi

# --- Never Allowed: a lint/type rule silenced without explanation (Operational Guardrails, "Never allowed") ---
SUPPRESSIONS=$(echo "$FILES" | xargs -r grep -InE '(eslint-disable|# noqa|# type: ignore|@ts-ignore|#\[allow\()' 2>/dev/null || true)
if [ -n "$SUPPRESSIONS" ]; then
  echo "::warning::Lint/type suppression(s) found — confirm each was discussed, not used to bypass a real issue:"
  echo "$SUPPRESSIONS"
fi

# --- Never Allowed: a force-push marker left in a script, or a destructive git alias committed ---
if echo "$FILES" | xargs -r grep -InE 'git (push --force|reset --hard)\b' 2>/dev/null | grep -v -E '\.md:' ; then
  say_fail "A destructive git command (--force / reset --hard) is committed in a script — this repo's guardrails forbid rewriting shared history."
fi

if [ "$FAIL" -eq 1 ]; then
  echo ""
  echo "One or more Agent Hub guardrails were violated — see the errors above. These map directly to the"
  echo "Operational Guardrails / Universal Guardrails sections in this repo's agent instruction file(s)."
  exit 1
fi

echo "No guardrail violations found."
# Primary surface this check pays closest attention to (informational only): src/**/*.tsx, src/**/*.jsx, src/app/**/*.tsx, src/app/**/route.ts, prisma/schema.prisma, **/*.sql, src/**/*.ts, **/*.ts, **/*.tsx, tsconfig.json, **/migrations/**, **/models/**, **/schemas/**, **/*.mongo.*, **/*.jsx, **/*.vue, tailwind.config.*
